#!/bin/sh

GRAALVM_HOME="/usr/lib/jvm/java-17-graalvm"
"$GRAALVM_HOME/bin/gu" install native-image

"$GRAALVM_HOME/bin/native-image" \
    -jar target/mensascrap2*.jar \
    -H:Name=mensascrap2 \
    -H:+ReportExceptionStackTraces \
    --enable-url-protocols=https \
    --verbose \
    --no-fallback \
    --no-server \
    "-J-Xmx3g"
