name: "continous awesomeness"
on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  dominant_architecture:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    # SETUP
      - name: checkout
        uses: actions/checkout@master

      - name: prepare java
        uses: actions/setup-java@v3.11.0
        with: 
          distribution: 'zulu'
          java-version: '17'
          
      - name: install clojure tools
        uses: DeLaGuardo/setup-clojure@10.3
        with: 
          cli: 'latest'
    
    # COMMIT 1
      - name: generate master.json
        run: echo "out=$(clojure -M -m mensascrap2.core)" >> $GITHUB_ENV
      
      - name: generate commitmessage
        run: echo "msg=$(clojure -M -m mensascrap2.core heh)" >> $GITHUB_ENV

      - name: write master.json
        run: echo "${{ env.out }}" > docs/master.json

      - name: auwuto commit uwu
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "${{ env.msg }}"
          repository: .
          file_pattern: docs/master.json
          commit_author: port19 <port19@port19.xyz>
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    # COMMIT 2
      - name: generate master.json
        run: echo "out=$(clojure -M -m mensascrap2.core)" >> $GITHUB_ENV
      
      - name: generate commitmessage
        run: echo "msg=$(clojure -M -m mensascrap2.core heh hoh)" >> $GITHUB_ENV

      - name: write master.json
        run: echo "${{ env.out }}" > docs/master.json

      - name: auwuto commit uwu
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "${{ env.msg }}"
          repository: .
          file_pattern: docs/master.json
          commit_author: port19 <port19@port19.xyz>
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
