name: "continous awesomeness"
on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 7 * * *"

jobs:
  dominant_architecture:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: prepare java
        uses: actions/setup-java@v3.11.0
        with: 
          distribution: 'zulu'
          java-version: '17'
          
      - name: install clojure tools
        uses: DeLaGuardo/setup-clojure@10.3
        with: 
          cli: 'latest'
    
      - name: generate & write master.json
        run: clojure -M -m mensascrap2.core > docs/master.json
      
      - name: auwuto commit uwu
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: bump master.json
          repository: .
          file_pattern: docs/master.json
          commit_author: port19 <port19@port19.xyz>
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
